language: generic

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_script:
  - pip3 install pykwalify

script:
  - pykwalify -s data/uni/schema.yaml -d data/uni/unis.yaml -e data/uni/extensions.py